### ISSUE TITLE
User Input UI

### ISSUE THREAD

**Issue by chanon-mike** [chanon-mike/smart-ryokou#8]
## Summary
UI for the main page, there are a input bar for prompt asking
[Figma](https://www.figma.com/file/TXTmhow5ovM3eZjOZy3ID5/FirstDraft-HomePage?type=design&node-id=0-1&mode=design)

## Expected Behavior
Input bar is displayed

**Comment by student158** [comment]
Why there is birthday field in this page?

![Image](https://github.com/chanon-mike/smart-ryokou/assets/56637459/f464e809-db3e-4a67-bac5-e41dcec658ec)

As I understand, we want to set recommendation based on user's age?

**Comment by chanon-mike** [comment]
Yeah... I also don't understand here...

I will make changes to the design this weekend.
